name: Bug report
description: Something not working as expected? Let us look into it.
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      value: "*Please describe.*\n*If this affects the front-end, screenshots would be of great help.*\n\n* This speeds up our ability to troubleshoot tremendously.*\n\n## How to reproduce\n\n1. \n2.\n3. \n\n## Additional context\n\n"

  - type: textarea
    id: debug-info
    attributes:
      label: Debug info
      render: shell

  - type: markdown
    attributes:
      value: "#### *Thank you* for your bug report – we love squashing them!"
